--------------------------
-- TABLA TP_D_USUARIOS  -- 
--------------------------

USE `TravelPlanner`;

CREATE TABLE TP_D_USUARIOS (
    TP_ID_SECUENCIAL BIGINT (20) NOT NULL AUTO_INCREMENT,
    TP_TX_USUARIO VARCHAR (32) NOT NULL,
    TP_TX_CONTRASENIA VARCHAR (32) NOT NULL,
    TP_ID_TIPOCUENTA BIGINT NOT NULL,
    TP_TX_NOMBRE VARCHAR (32) NOT NULL,
    TP_TX_APELLIDO1 VARCHAR (32) NOT NULL,
    TP_TX_APELLIDO2 VARCHAR (32) NOT NULL,
    TP_TX_CORREO VARCHAR (32) NOT NULL,
    TP_LB_FOTO LONGBLOB,   
    TP_LG_HABILITADO BOOL NOT NULL,
    TP_LG_ELIMINADO BOOL NOT NULL,
    TP_DT_CREACION TIMESTAMP NOT NULL,
    TP_DT_MODIFICACION TIMESTAMP NOT NULL,
    PRIMARY KEY (TP_ID_SECUENCIAL),
    FOREIGN KEY (TP_ID_TIPOCUENTA) REFERENCES TP_P_TIPOS_CUENTA(TP_ID_SECUENCIAL)
);

CREATE INDEX TP_D_USUARIOS_ID ON TP_D_USUARIOS(TP_ID_SECUENCIAL); 