export var GLOBAL = {   
    idUsuario: null,
    vistaSeleccionada: '',
    uri: 'http://localhost/TravelPlanner/index.php/',
    url_email: 'http://localhost/TravelPlanner/email.php/',
    recurs_error: "error",
    recurs_addUsuario: 'addUsuarios',
    recurs_getUsuario: 'getUsuario/',
    recurs_getInforUsuario: 'getInforUsuario/',
    recurs_usuario_mail:'usuario_mail/',
    recurs_setUsuario: 'setUsuario/',   
    recurs_deleteUsuario: 'deleteUsuario/',
    recurs_uploadImage: 'subirImagen/',
    recurs_getCiudades: 'getCiudades',
    recurs_getPreferencias: 'getPreferencias',
    recurs_getPreferenciasConfiguracion: 'getPreferencias/',
    recurs_getMapasPendientes: 'getMapasPendientes/',
    recurs_getHistorialMapas: 'getHistorialMapas/',
    recurs_getMarcadores: 'getMarcadores/',
    recurs_getConfiguracion: 'getConfiguracion/',
    recurs_addConfiguracion: 'addConfiguracion',
    recurs_deleteMapa: 'deleteMapa/',
    recurs_addValoracion: 'addValoracion/',
    recurs_habilitarMapa: 'habilitarMapa/',
    recurs_getMapa: 'getMapa/',
    latidud_defecto:37.389092,
    longitud_defecto:-5.984459,
    zoom_defecto:10
};
